# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import manhole_pb2 as manhole__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in manhole_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NodeMonitorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetHardwareStaticInfo = channel.unary_unary(
                '/manhole.NodeMonitor/GetHardwareStaticInfo',
                request_serializer=manhole__pb2.Empty.SerializeToString,
                response_deserializer=manhole__pb2.HardwareStaticInfo.FromString,
                _registered_method=True)
        self.StreamDynamicStats = channel.unary_stream(
                '/manhole.NodeMonitor/StreamDynamicStats',
                request_serializer=manhole__pb2.Empty.SerializeToString,
                response_deserializer=manhole__pb2.DynamicStatsResponse.FromString,
                _registered_method=True)


class NodeMonitorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetHardwareStaticInfo(self, request, context):
        """Pobierz konfigurację sprzętową (wywołaj raz)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamDynamicStats(self, request, context):
        """Subskrybuj strumień statystyk (wywołuj co sekundę)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeMonitorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetHardwareStaticInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHardwareStaticInfo,
                    request_deserializer=manhole__pb2.Empty.FromString,
                    response_serializer=manhole__pb2.HardwareStaticInfo.SerializeToString,
            ),
            'StreamDynamicStats': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamDynamicStats,
                    request_deserializer=manhole__pb2.Empty.FromString,
                    response_serializer=manhole__pb2.DynamicStatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'manhole.NodeMonitor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('manhole.NodeMonitor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NodeMonitor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetHardwareStaticInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/manhole.NodeMonitor/GetHardwareStaticInfo',
            manhole__pb2.Empty.SerializeToString,
            manhole__pb2.HardwareStaticInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamDynamicStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/manhole.NodeMonitor/StreamDynamicStats',
            manhole__pb2.Empty.SerializeToString,
            manhole__pb2.DynamicStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
