# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: manhole.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'manhole.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmanhole.proto\"D\n\x07\x43puInfo\x12\x0e\n\x06\x63pu_id\x18\x01 \x01(\x05\x12\x14\n\x0cthread_usage\x18\x02 \x01(\x05\x12\x13\n\x0btemperature\x18\x03 \x01(\x01\"B\n\x07GpuInfo\x12\x0e\n\x06gpu_id\x18\x01 \x01(\x05\x12\x12\n\nvram_usage\x18\x02 \x01(\x01\x12\x13\n\x0btemperature\x18\x03 \x01(\x01\"^\n\tHeartbeat\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x16\n\x04\x63pus\x18\x02 \x03(\x0b\x32\x08.CpuInfo\x12\x16\n\x04gpus\x18\x03 \x03(\x0b\x32\x08.GpuInfo\x12\x11\n\tram_usage\x18\x04 \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'manhole_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CPUINFO']._serialized_start=17
  _globals['_CPUINFO']._serialized_end=85
  _globals['_GPUINFO']._serialized_start=87
  _globals['_GPUINFO']._serialized_end=153
  _globals['_HEARTBEAT']._serialized_start=155
  _globals['_HEARTBEAT']._serialized_end=249
# @@protoc_insertion_point(module_scope)
