# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: manhole.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'manhole.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmanhole.proto\x12\x07manhole\"\x07\n\x05\x45mpty\"5\n\tGpuStatic\x12\x0e\n\x06gpu_id\x18\x01 \x01(\x05\x12\x18\n\x10total_vram_bytes\x18\x02 \x01(\x04\"{\n\x12HardwareStaticInfo\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x17\n\x0ftotal_ram_bytes\x18\x02 \x01(\x04\x12\x19\n\x11\x63pu_sockets_count\x18\x03 \x01(\x05\x12 \n\x04gpus\x18\x04 \x03(\x0b\x32\x12.manhole.GpuStatic\"H\n\nCpuDynamic\x12\x0e\n\x06\x63pu_id\x18\x01 \x01(\x05\x12\x15\n\rusage_percent\x18\x02 \x01(\x01\x12\x13\n\x0btemperature\x18\x03 \x01(\x01\"J\n\nGpuDynamic\x12\x0e\n\x06gpu_id\x18\x01 \x01(\x05\x12\x17\n\x0fvram_used_bytes\x18\x02 \x01(\x04\x12\x13\n\x0btemperature\x18\x03 \x01(\x01\"\x84\x01\n\x14\x44ynamicStatsResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x16\n\x0eram_used_bytes\x18\x02 \x01(\x04\x12!\n\x04\x63pus\x18\x03 \x03(\x0b\x32\x13.manhole.CpuDynamic\x12!\n\x04gpus\x18\x04 \x03(\x0b\x32\x13.manhole.GpuDynamic2\x9a\x01\n\x0bNodeMonitor\x12\x44\n\x15GetHardwareStaticInfo\x12\x0e.manhole.Empty\x1a\x1b.manhole.HardwareStaticInfo\x12\x45\n\x12StreamDynamicStats\x12\x0e.manhole.Empty\x1a\x1d.manhole.DynamicStatsResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'manhole_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=26
  _globals['_EMPTY']._serialized_end=33
  _globals['_GPUSTATIC']._serialized_start=35
  _globals['_GPUSTATIC']._serialized_end=88
  _globals['_HARDWARESTATICINFO']._serialized_start=90
  _globals['_HARDWARESTATICINFO']._serialized_end=213
  _globals['_CPUDYNAMIC']._serialized_start=215
  _globals['_CPUDYNAMIC']._serialized_end=287
  _globals['_GPUDYNAMIC']._serialized_start=289
  _globals['_GPUDYNAMIC']._serialized_end=363
  _globals['_DYNAMICSTATSRESPONSE']._serialized_start=366
  _globals['_DYNAMICSTATSRESPONSE']._serialized_end=498
  _globals['_NODEMONITOR']._serialized_start=501
  _globals['_NODEMONITOR']._serialized_end=655
# @@protoc_insertion_point(module_scope)
