// <auto-generated />
using System;
using DefaultNamespace;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace sewers.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260328091714_ModifyDailyWindow")]
    partial class ModifyDailyWindow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("sewers.Model.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("sewers.Model.Cpu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CpuId")
                        .HasColumnType("int");

                    b.Property<Guid>("ManholeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Threads")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ManholeId");

                    b.ToTable("Cpu");
                });

            modelBuilder.Entity("sewers.Model.Gpu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GpuId")
                        .HasColumnType("int");

                    b.Property<Guid>("ManholeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Vram")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ManholeId");

                    b.ToTable("Gpu");
                });

            modelBuilder.Entity("sewers.Model.Manhole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CityLatitude")
                        .HasColumnType("float");

                    b.Property<double>("CityLongitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("PricePerTeraflop")
                        .HasColumnType("float");

                    b.Property<double>("RAM")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Manholes");
                });

            modelBuilder.Entity("sewers.Model.Cpu", b =>
                {
                    b.HasOne("sewers.Model.Manhole", "Manhole")
                        .WithMany("CPUs")
                        .HasForeignKey("ManholeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manhole");
                });

            modelBuilder.Entity("sewers.Model.Gpu", b =>
                {
                    b.HasOne("sewers.Model.Manhole", "Manhole")
                        .WithMany("GPUs")
                        .HasForeignKey("ManholeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manhole");
                });

            modelBuilder.Entity("sewers.Model.Manhole", b =>
                {
                    b.HasOne("sewers.Model.Company", "Owner")
                        .WithMany("Manholes")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("sewers.Model.WindowSchedule", "WindowSchedule", b1 =>
                        {
                            b1.Property<Guid>("ManholeId");

                            b1.HasKey("ManholeId");

                            b1.ToTable("Manholes");

                            b1.ToJson("WindowSchedule");

                            b1.WithOwner()
                                .HasForeignKey("ManholeId");

                            b1.OwnsOne("sewers.Model.DailyWindow", "Friday", b2 =>
                                {
                                    b2.Property<Guid>("WindowScheduleManholeId");

                                    b2.Property<string>("WindowEnd")
                                        .IsRequired();

                                    b2.Property<string>("WindowStart")
                                        .IsRequired();

                                    b2.HasKey("WindowScheduleManholeId");

                                    b2.ToTable("Manholes");

                                    b2.WithOwner()
                                        .HasForeignKey("WindowScheduleManholeId");
                                });

                            b1.OwnsOne("sewers.Model.DailyWindow", "Monday", b2 =>
                                {
                                    b2.Property<Guid>("WindowScheduleManholeId");

                                    b2.Property<string>("WindowEnd")
                                        .IsRequired();

                                    b2.Property<string>("WindowStart")
                                        .IsRequired();

                                    b2.HasKey("WindowScheduleManholeId");

                                    b2.ToTable("Manholes");

                                    b2.WithOwner()
                                        .HasForeignKey("WindowScheduleManholeId");
                                });

                            b1.OwnsOne("sewers.Model.DailyWindow", "Saturday", b2 =>
                                {
                                    b2.Property<Guid>("WindowScheduleManholeId");

                                    b2.Property<string>("WindowEnd")
                                        .IsRequired();

                                    b2.Property<string>("WindowStart")
                                        .IsRequired();

                                    b2.HasKey("WindowScheduleManholeId");

                                    b2.ToTable("Manholes");

                                    b2.WithOwner()
                                        .HasForeignKey("WindowScheduleManholeId");
                                });

                            b1.OwnsOne("sewers.Model.DailyWindow", "Sunday", b2 =>
                                {
                                    b2.Property<Guid>("WindowScheduleManholeId");

                                    b2.Property<string>("WindowEnd")
                                        .IsRequired();

                                    b2.Property<string>("WindowStart")
                                        .IsRequired();

                                    b2.HasKey("WindowScheduleManholeId");

                                    b2.ToTable("Manholes");

                                    b2.WithOwner()
                                        .HasForeignKey("WindowScheduleManholeId");
                                });

                            b1.OwnsOne("sewers.Model.DailyWindow", "Thursday", b2 =>
                                {
                                    b2.Property<Guid>("WindowScheduleManholeId");

                                    b2.Property<string>("WindowEnd")
                                        .IsRequired();

                                    b2.Property<string>("WindowStart")
                                        .IsRequired();

                                    b2.HasKey("WindowScheduleManholeId");

                                    b2.ToTable("Manholes");

                                    b2.WithOwner()
                                        .HasForeignKey("WindowScheduleManholeId");
                                });

                            b1.OwnsOne("sewers.Model.DailyWindow", "Tuesday", b2 =>
                                {
                                    b2.Property<Guid>("WindowScheduleManholeId");

                                    b2.Property<string>("WindowEnd")
                                        .IsRequired();

                                    b2.Property<string>("WindowStart")
                                        .IsRequired();

                                    b2.HasKey("WindowScheduleManholeId");

                                    b2.ToTable("Manholes");

                                    b2.WithOwner()
                                        .HasForeignKey("WindowScheduleManholeId");
                                });

                            b1.OwnsOne("sewers.Model.DailyWindow", "Wednesday", b2 =>
                                {
                                    b2.Property<Guid>("WindowScheduleManholeId");

                                    b2.Property<string>("WindowEnd")
                                        .IsRequired();

                                    b2.Property<string>("WindowStart")
                                        .IsRequired();

                                    b2.HasKey("WindowScheduleManholeId");

                                    b2.ToTable("Manholes");

                                    b2.WithOwner()
                                        .HasForeignKey("WindowScheduleManholeId");
                                });

                            b1.Navigation("Friday");

                            b1.Navigation("Monday");

                            b1.Navigation("Saturday");

                            b1.Navigation("Sunday");

                            b1.Navigation("Thursday");

                            b1.Navigation("Tuesday");

                            b1.Navigation("Wednesday");
                        });

                    b.Navigation("Owner");

                    b.Navigation("WindowSchedule")
                        .IsRequired();
                });

            modelBuilder.Entity("sewers.Model.Company", b =>
                {
                    b.Navigation("Manholes");
                });

            modelBuilder.Entity("sewers.Model.Manhole", b =>
                {
                    b.Navigation("CPUs");

                    b.Navigation("GPUs");
                });
#pragma warning restore 612, 618
        }
    }
}
