/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/agents/': RouteRecordInfo<
      '/agents/',
      '/agents',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/api-docs/': RouteRecordInfo<
      '/api-docs/',
      '/api-docs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/billing/': RouteRecordInfo<
      '/billing/',
      '/billing',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/': RouteRecordInfo<
      '/dashboard/',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/ServerDetailsModal': RouteRecordInfo<
      '/dashboard/ServerDetailsModal',
      '/dashboard/ServerDetailsModal',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/example/': RouteRecordInfo<
      '/example/',
      '/example',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/providers/': RouteRecordInfo<
      '/providers/',
      '/providers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tasks/': RouteRecordInfo<
      '/tasks/',
      '/tasks',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/agents/index.vue': {
      routes:
        | '/agents/'
      views:
        | never
    }
    'src/pages/api-docs/index.vue': {
      routes:
        | '/api-docs/'
      views:
        | never
    }
    'src/pages/billing/index.vue': {
      routes:
        | '/billing/'
      views:
        | never
    }
    'src/pages/dashboard/index.vue': {
      routes:
        | '/dashboard/'
      views:
        | never
    }
    'src/pages/dashboard/ServerDetailsModal.vue': {
      routes:
        | '/dashboard/ServerDetailsModal'
      views:
        | never
    }
    'src/pages/example/index.vue': {
      routes:
        | '/example/'
      views:
        | never
    }
    'src/pages/providers/index.vue': {
      routes:
        | '/providers/'
      views:
        | never
    }
    'src/pages/tasks/index.vue': {
      routes:
        | '/tasks/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
