// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.1
// source: main.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Observable } from "rxjs";
import { map } from "rxjs/operators";

export const protobufPackage = "sewers";

export interface Server {
  id: string;
  gpu: string;
  vram: string;
  ram: string;
  cpuThreads: number;
  pricePerTflops: number;
  load: number;
  status: string;
  availability: string;
}

export interface Company {
  id: string;
  name: string;
  status: string;
  servers: Server[];
}

export interface Cluster {
  id: string;
  name: string;
  lat: number;
  lng: number;
  status: string;
  companies: Company[];
}

export interface User {
  id: string;
  name: string;
  avatar: string;
  role: string;
  balance: number;
  currency: string;
}

export interface Metrics {
  onlineNodes: number;
  totalVram: string;
  queuedTasks: number;
  companies: number;
  gpus: number;
}

export interface Task {
  id: number;
  name: string;
  type: string;
  model: string;
  status: string;
  progress: number;
}

export interface TaskType {
  value: string;
  label: string;
  icon: string;
  description: string;
}

export interface GetConfigRequest {
}

export interface ConfigResponse {
  metrics: Metrics | undefined;
  clusters: Cluster[];
  currentUser: User | undefined;
  taskTypes: TaskType[];
  availableModels: string[];
}

export interface GetTasksRequest {
}

export interface GetTasksResponse {
  tasks: Task[];
}

export interface CreateTaskRequest {
  name: string;
  type: string;
  baseModel: string;
  priority: number;
}

export interface CreateTaskResponse {
  task: Task | undefined;
  success: boolean;
  message: string;
}

export interface RemoveTaskRequest {
  id: number;
}

export interface RemoveTaskResponse {
  success: boolean;
  message: string;
}

export interface EditTaskRequest {
  id: number;
  name: string;
  type: string;
  model: string;
}

export interface EditTaskResponse {
  task: Task | undefined;
  success: boolean;
  message: string;
}

export interface PauseTaskRequest {
  id: number;
}

export interface PauseTaskResponse {
  task: Task | undefined;
  success: boolean;
  message: string;
}

export interface StopTaskRequest {
  id: number;
}

export interface StopTaskResponse {
  task: Task | undefined;
  success: boolean;
  message: string;
}

export interface Invoice {
  id: string;
  date: string;
  amount: number;
  status: string;
}

export interface GetBillingRequest {
}

export interface GetBillingResponse {
  invoices: Invoice[];
  currentMonthSpending: number;
  hourlyRate: number;
  dailySpending: number[];
  resourceUsage: number[];
}

function createBaseServer(): Server {
  return {
    id: "",
    gpu: "",
    vram: "",
    ram: "",
    cpuThreads: 0,
    pricePerTflops: 0,
    load: 0,
    status: "",
    availability: "",
  };
}

export const Server: MessageFns<Server> = {
  encode(message: Server, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.gpu !== "") {
      writer.uint32(18).string(message.gpu);
    }
    if (message.vram !== "") {
      writer.uint32(26).string(message.vram);
    }
    if (message.ram !== "") {
      writer.uint32(34).string(message.ram);
    }
    if (message.cpuThreads !== 0) {
      writer.uint32(40).int32(message.cpuThreads);
    }
    if (message.pricePerTflops !== 0) {
      writer.uint32(49).double(message.pricePerTflops);
    }
    if (message.load !== 0) {
      writer.uint32(56).int32(message.load);
    }
    if (message.status !== "") {
      writer.uint32(66).string(message.status);
    }
    if (message.availability !== "") {
      writer.uint32(74).string(message.availability);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Server {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServer();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.gpu = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.vram = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.ram = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.cpuThreads = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 49) {
            break;
          }

          message.pricePerTflops = reader.double();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.load = reader.int32();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.availability = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Server {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      gpu: isSet(object.gpu) ? globalThis.String(object.gpu) : "",
      vram: isSet(object.vram) ? globalThis.String(object.vram) : "",
      ram: isSet(object.ram) ? globalThis.String(object.ram) : "",
      cpuThreads: isSet(object.cpuThreads)
        ? globalThis.Number(object.cpuThreads)
        : isSet(object.cpu_threads)
        ? globalThis.Number(object.cpu_threads)
        : 0,
      pricePerTflops: isSet(object.pricePerTflops)
        ? globalThis.Number(object.pricePerTflops)
        : isSet(object.price_per_tflops)
        ? globalThis.Number(object.price_per_tflops)
        : 0,
      load: isSet(object.load) ? globalThis.Number(object.load) : 0,
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      availability: isSet(object.availability) ? globalThis.String(object.availability) : "",
    };
  },

  toJSON(message: Server): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.gpu !== "") {
      obj.gpu = message.gpu;
    }
    if (message.vram !== "") {
      obj.vram = message.vram;
    }
    if (message.ram !== "") {
      obj.ram = message.ram;
    }
    if (message.cpuThreads !== 0) {
      obj.cpuThreads = Math.round(message.cpuThreads);
    }
    if (message.pricePerTflops !== 0) {
      obj.pricePerTflops = message.pricePerTflops;
    }
    if (message.load !== 0) {
      obj.load = Math.round(message.load);
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.availability !== "") {
      obj.availability = message.availability;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Server>, I>>(base?: I): Server {
    return Server.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Server>, I>>(object: I): Server {
    const message = createBaseServer();
    message.id = object.id ?? "";
    message.gpu = object.gpu ?? "";
    message.vram = object.vram ?? "";
    message.ram = object.ram ?? "";
    message.cpuThreads = object.cpuThreads ?? 0;
    message.pricePerTflops = object.pricePerTflops ?? 0;
    message.load = object.load ?? 0;
    message.status = object.status ?? "";
    message.availability = object.availability ?? "";
    return message;
  },
};

function createBaseCompany(): Company {
  return { id: "", name: "", status: "", servers: [] };
}

export const Company: MessageFns<Company> = {
  encode(message: Company, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.status !== "") {
      writer.uint32(26).string(message.status);
    }
    for (const v of message.servers) {
      Server.encode(v!, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Company {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCompany();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.servers.push(Server.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Company {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      servers: globalThis.Array.isArray(object?.servers) ? object.servers.map((e: any) => Server.fromJSON(e)) : [],
    };
  },

  toJSON(message: Company): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.servers?.length) {
      obj.servers = message.servers.map((e) => Server.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Company>, I>>(base?: I): Company {
    return Company.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Company>, I>>(object: I): Company {
    const message = createBaseCompany();
    message.id = object.id ?? "";
    message.name = object.name ?? "";
    message.status = object.status ?? "";
    message.servers = object.servers?.map((e) => Server.fromPartial(e)) || [];
    return message;
  },
};

function createBaseCluster(): Cluster {
  return { id: "", name: "", lat: 0, lng: 0, status: "", companies: [] };
}

export const Cluster: MessageFns<Cluster> = {
  encode(message: Cluster, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.lat !== 0) {
      writer.uint32(25).double(message.lat);
    }
    if (message.lng !== 0) {
      writer.uint32(33).double(message.lng);
    }
    if (message.status !== "") {
      writer.uint32(42).string(message.status);
    }
    for (const v of message.companies) {
      Company.encode(v!, writer.uint32(50).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Cluster {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCluster();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.lat = reader.double();
          continue;
        }
        case 4: {
          if (tag !== 33) {
            break;
          }

          message.lng = reader.double();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.companies.push(Company.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Cluster {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      lat: isSet(object.lat) ? globalThis.Number(object.lat) : 0,
      lng: isSet(object.lng) ? globalThis.Number(object.lng) : 0,
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      companies: globalThis.Array.isArray(object?.companies)
        ? object.companies.map((e: any) => Company.fromJSON(e))
        : [],
    };
  },

  toJSON(message: Cluster): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.lat !== 0) {
      obj.lat = message.lat;
    }
    if (message.lng !== 0) {
      obj.lng = message.lng;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.companies?.length) {
      obj.companies = message.companies.map((e) => Company.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Cluster>, I>>(base?: I): Cluster {
    return Cluster.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Cluster>, I>>(object: I): Cluster {
    const message = createBaseCluster();
    message.id = object.id ?? "";
    message.name = object.name ?? "";
    message.lat = object.lat ?? 0;
    message.lng = object.lng ?? 0;
    message.status = object.status ?? "";
    message.companies = object.companies?.map((e) => Company.fromPartial(e)) || [];
    return message;
  },
};

function createBaseUser(): User {
  return { id: "", name: "", avatar: "", role: "", balance: 0, currency: "" };
}

export const User: MessageFns<User> = {
  encode(message: User, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.avatar !== "") {
      writer.uint32(26).string(message.avatar);
    }
    if (message.role !== "") {
      writer.uint32(34).string(message.role);
    }
    if (message.balance !== 0) {
      writer.uint32(41).double(message.balance);
    }
    if (message.currency !== "") {
      writer.uint32(50).string(message.currency);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): User {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUser();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.avatar = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.role = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 41) {
            break;
          }

          message.balance = reader.double();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.currency = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): User {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      avatar: isSet(object.avatar) ? globalThis.String(object.avatar) : "",
      role: isSet(object.role) ? globalThis.String(object.role) : "",
      balance: isSet(object.balance) ? globalThis.Number(object.balance) : 0,
      currency: isSet(object.currency) ? globalThis.String(object.currency) : "",
    };
  },

  toJSON(message: User): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.avatar !== "") {
      obj.avatar = message.avatar;
    }
    if (message.role !== "") {
      obj.role = message.role;
    }
    if (message.balance !== 0) {
      obj.balance = message.balance;
    }
    if (message.currency !== "") {
      obj.currency = message.currency;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<User>, I>>(base?: I): User {
    return User.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<User>, I>>(object: I): User {
    const message = createBaseUser();
    message.id = object.id ?? "";
    message.name = object.name ?? "";
    message.avatar = object.avatar ?? "";
    message.role = object.role ?? "";
    message.balance = object.balance ?? 0;
    message.currency = object.currency ?? "";
    return message;
  },
};

function createBaseMetrics(): Metrics {
  return { onlineNodes: 0, totalVram: "", queuedTasks: 0, companies: 0, gpus: 0 };
}

export const Metrics: MessageFns<Metrics> = {
  encode(message: Metrics, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.onlineNodes !== 0) {
      writer.uint32(8).int32(message.onlineNodes);
    }
    if (message.totalVram !== "") {
      writer.uint32(18).string(message.totalVram);
    }
    if (message.queuedTasks !== 0) {
      writer.uint32(24).int32(message.queuedTasks);
    }
    if (message.companies !== 0) {
      writer.uint32(32).int32(message.companies);
    }
    if (message.gpus !== 0) {
      writer.uint32(40).int32(message.gpus);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Metrics {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMetrics();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.onlineNodes = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.totalVram = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.queuedTasks = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.companies = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.gpus = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Metrics {
    return {
      onlineNodes: isSet(object.onlineNodes)
        ? globalThis.Number(object.onlineNodes)
        : isSet(object.online_nodes)
        ? globalThis.Number(object.online_nodes)
        : 0,
      totalVram: isSet(object.totalVram)
        ? globalThis.String(object.totalVram)
        : isSet(object.total_vram)
        ? globalThis.String(object.total_vram)
        : "",
      queuedTasks: isSet(object.queuedTasks)
        ? globalThis.Number(object.queuedTasks)
        : isSet(object.queued_tasks)
        ? globalThis.Number(object.queued_tasks)
        : 0,
      companies: isSet(object.companies) ? globalThis.Number(object.companies) : 0,
      gpus: isSet(object.gpus) ? globalThis.Number(object.gpus) : 0,
    };
  },

  toJSON(message: Metrics): unknown {
    const obj: any = {};
    if (message.onlineNodes !== 0) {
      obj.onlineNodes = Math.round(message.onlineNodes);
    }
    if (message.totalVram !== "") {
      obj.totalVram = message.totalVram;
    }
    if (message.queuedTasks !== 0) {
      obj.queuedTasks = Math.round(message.queuedTasks);
    }
    if (message.companies !== 0) {
      obj.companies = Math.round(message.companies);
    }
    if (message.gpus !== 0) {
      obj.gpus = Math.round(message.gpus);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Metrics>, I>>(base?: I): Metrics {
    return Metrics.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Metrics>, I>>(object: I): Metrics {
    const message = createBaseMetrics();
    message.onlineNodes = object.onlineNodes ?? 0;
    message.totalVram = object.totalVram ?? "";
    message.queuedTasks = object.queuedTasks ?? 0;
    message.companies = object.companies ?? 0;
    message.gpus = object.gpus ?? 0;
    return message;
  },
};

function createBaseTask(): Task {
  return { id: 0, name: "", type: "", model: "", status: "", progress: 0 };
}

export const Task: MessageFns<Task> = {
  encode(message: Task, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.type !== "") {
      writer.uint32(26).string(message.type);
    }
    if (message.model !== "") {
      writer.uint32(34).string(message.model);
    }
    if (message.status !== "") {
      writer.uint32(42).string(message.status);
    }
    if (message.progress !== 0) {
      writer.uint32(48).int32(message.progress);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Task {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTask();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.model = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.progress = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Task {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      model: isSet(object.model) ? globalThis.String(object.model) : "",
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      progress: isSet(object.progress) ? globalThis.Number(object.progress) : 0,
    };
  },

  toJSON(message: Task): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.type !== "") {
      obj.type = message.type;
    }
    if (message.model !== "") {
      obj.model = message.model;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.progress !== 0) {
      obj.progress = Math.round(message.progress);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Task>, I>>(base?: I): Task {
    return Task.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Task>, I>>(object: I): Task {
    const message = createBaseTask();
    message.id = object.id ?? 0;
    message.name = object.name ?? "";
    message.type = object.type ?? "";
    message.model = object.model ?? "";
    message.status = object.status ?? "";
    message.progress = object.progress ?? 0;
    return message;
  },
};

function createBaseTaskType(): TaskType {
  return { value: "", label: "", icon: "", description: "" };
}

export const TaskType: MessageFns<TaskType> = {
  encode(message: TaskType, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.value !== "") {
      writer.uint32(10).string(message.value);
    }
    if (message.label !== "") {
      writer.uint32(18).string(message.label);
    }
    if (message.icon !== "") {
      writer.uint32(26).string(message.icon);
    }
    if (message.description !== "") {
      writer.uint32(34).string(message.description);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TaskType {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTaskType();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.value = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.label = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.icon = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.description = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TaskType {
    return {
      value: isSet(object.value) ? globalThis.String(object.value) : "",
      label: isSet(object.label) ? globalThis.String(object.label) : "",
      icon: isSet(object.icon) ? globalThis.String(object.icon) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
    };
  },

  toJSON(message: TaskType): unknown {
    const obj: any = {};
    if (message.value !== "") {
      obj.value = message.value;
    }
    if (message.label !== "") {
      obj.label = message.label;
    }
    if (message.icon !== "") {
      obj.icon = message.icon;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TaskType>, I>>(base?: I): TaskType {
    return TaskType.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TaskType>, I>>(object: I): TaskType {
    const message = createBaseTaskType();
    message.value = object.value ?? "";
    message.label = object.label ?? "";
    message.icon = object.icon ?? "";
    message.description = object.description ?? "";
    return message;
  },
};

function createBaseGetConfigRequest(): GetConfigRequest {
  return {};
}

export const GetConfigRequest: MessageFns<GetConfigRequest> = {
  encode(_: GetConfigRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetConfigRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetConfigRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetConfigRequest {
    return {};
  },

  toJSON(_: GetConfigRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GetConfigRequest>, I>>(base?: I): GetConfigRequest {
    return GetConfigRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetConfigRequest>, I>>(_: I): GetConfigRequest {
    const message = createBaseGetConfigRequest();
    return message;
  },
};

function createBaseConfigResponse(): ConfigResponse {
  return { metrics: undefined, clusters: [], currentUser: undefined, taskTypes: [], availableModels: [] };
}

export const ConfigResponse: MessageFns<ConfigResponse> = {
  encode(message: ConfigResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.metrics !== undefined) {
      Metrics.encode(message.metrics, writer.uint32(10).fork()).join();
    }
    for (const v of message.clusters) {
      Cluster.encode(v!, writer.uint32(18).fork()).join();
    }
    if (message.currentUser !== undefined) {
      User.encode(message.currentUser, writer.uint32(26).fork()).join();
    }
    for (const v of message.taskTypes) {
      TaskType.encode(v!, writer.uint32(34).fork()).join();
    }
    for (const v of message.availableModels) {
      writer.uint32(42).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ConfigResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConfigResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.metrics = Metrics.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.clusters.push(Cluster.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.currentUser = User.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.taskTypes.push(TaskType.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.availableModels.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ConfigResponse {
    return {
      metrics: isSet(object.metrics) ? Metrics.fromJSON(object.metrics) : undefined,
      clusters: globalThis.Array.isArray(object?.clusters) ? object.clusters.map((e: any) => Cluster.fromJSON(e)) : [],
      currentUser: isSet(object.currentUser)
        ? User.fromJSON(object.currentUser)
        : isSet(object.current_user)
        ? User.fromJSON(object.current_user)
        : undefined,
      taskTypes: globalThis.Array.isArray(object?.taskTypes)
        ? object.taskTypes.map((e: any) => TaskType.fromJSON(e))
        : globalThis.Array.isArray(object?.task_types)
        ? object.task_types.map((e: any) => TaskType.fromJSON(e))
        : [],
      availableModels: globalThis.Array.isArray(object?.availableModels)
        ? object.availableModels.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.available_models)
        ? object.available_models.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: ConfigResponse): unknown {
    const obj: any = {};
    if (message.metrics !== undefined) {
      obj.metrics = Metrics.toJSON(message.metrics);
    }
    if (message.clusters?.length) {
      obj.clusters = message.clusters.map((e) => Cluster.toJSON(e));
    }
    if (message.currentUser !== undefined) {
      obj.currentUser = User.toJSON(message.currentUser);
    }
    if (message.taskTypes?.length) {
      obj.taskTypes = message.taskTypes.map((e) => TaskType.toJSON(e));
    }
    if (message.availableModels?.length) {
      obj.availableModels = message.availableModels;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ConfigResponse>, I>>(base?: I): ConfigResponse {
    return ConfigResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ConfigResponse>, I>>(object: I): ConfigResponse {
    const message = createBaseConfigResponse();
    message.metrics = (object.metrics !== undefined && object.metrics !== null)
      ? Metrics.fromPartial(object.metrics)
      : undefined;
    message.clusters = object.clusters?.map((e) => Cluster.fromPartial(e)) || [];
    message.currentUser = (object.currentUser !== undefined && object.currentUser !== null)
      ? User.fromPartial(object.currentUser)
      : undefined;
    message.taskTypes = object.taskTypes?.map((e) => TaskType.fromPartial(e)) || [];
    message.availableModels = object.availableModels?.map((e) => e) || [];
    return message;
  },
};

function createBaseGetTasksRequest(): GetTasksRequest {
  return {};
}

export const GetTasksRequest: MessageFns<GetTasksRequest> = {
  encode(_: GetTasksRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTasksRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTasksRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetTasksRequest {
    return {};
  },

  toJSON(_: GetTasksRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GetTasksRequest>, I>>(base?: I): GetTasksRequest {
    return GetTasksRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetTasksRequest>, I>>(_: I): GetTasksRequest {
    const message = createBaseGetTasksRequest();
    return message;
  },
};

function createBaseGetTasksResponse(): GetTasksResponse {
  return { tasks: [] };
}

export const GetTasksResponse: MessageFns<GetTasksResponse> = {
  encode(message: GetTasksResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.tasks) {
      Task.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTasksResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTasksResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.tasks.push(Task.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetTasksResponse {
    return { tasks: globalThis.Array.isArray(object?.tasks) ? object.tasks.map((e: any) => Task.fromJSON(e)) : [] };
  },

  toJSON(message: GetTasksResponse): unknown {
    const obj: any = {};
    if (message.tasks?.length) {
      obj.tasks = message.tasks.map((e) => Task.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetTasksResponse>, I>>(base?: I): GetTasksResponse {
    return GetTasksResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetTasksResponse>, I>>(object: I): GetTasksResponse {
    const message = createBaseGetTasksResponse();
    message.tasks = object.tasks?.map((e) => Task.fromPartial(e)) || [];
    return message;
  },
};

function createBaseCreateTaskRequest(): CreateTaskRequest {
  return { name: "", type: "", baseModel: "", priority: 0 };
}

export const CreateTaskRequest: MessageFns<CreateTaskRequest> = {
  encode(message: CreateTaskRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.type !== "") {
      writer.uint32(18).string(message.type);
    }
    if (message.baseModel !== "") {
      writer.uint32(26).string(message.baseModel);
    }
    if (message.priority !== 0) {
      writer.uint32(32).int32(message.priority);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateTaskRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateTaskRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.baseModel = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.priority = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateTaskRequest {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      baseModel: isSet(object.baseModel)
        ? globalThis.String(object.baseModel)
        : isSet(object.base_model)
        ? globalThis.String(object.base_model)
        : "",
      priority: isSet(object.priority) ? globalThis.Number(object.priority) : 0,
    };
  },

  toJSON(message: CreateTaskRequest): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.type !== "") {
      obj.type = message.type;
    }
    if (message.baseModel !== "") {
      obj.baseModel = message.baseModel;
    }
    if (message.priority !== 0) {
      obj.priority = Math.round(message.priority);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateTaskRequest>, I>>(base?: I): CreateTaskRequest {
    return CreateTaskRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateTaskRequest>, I>>(object: I): CreateTaskRequest {
    const message = createBaseCreateTaskRequest();
    message.name = object.name ?? "";
    message.type = object.type ?? "";
    message.baseModel = object.baseModel ?? "";
    message.priority = object.priority ?? 0;
    return message;
  },
};

function createBaseCreateTaskResponse(): CreateTaskResponse {
  return { task: undefined, success: false, message: "" };
}

export const CreateTaskResponse: MessageFns<CreateTaskResponse> = {
  encode(message: CreateTaskResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.task !== undefined) {
      Task.encode(message.task, writer.uint32(10).fork()).join();
    }
    if (message.success !== false) {
      writer.uint32(16).bool(message.success);
    }
    if (message.message !== "") {
      writer.uint32(26).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateTaskResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateTaskResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.task = Task.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateTaskResponse {
    return {
      task: isSet(object.task) ? Task.fromJSON(object.task) : undefined,
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
    };
  },

  toJSON(message: CreateTaskResponse): unknown {
    const obj: any = {};
    if (message.task !== undefined) {
      obj.task = Task.toJSON(message.task);
    }
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateTaskResponse>, I>>(base?: I): CreateTaskResponse {
    return CreateTaskResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateTaskResponse>, I>>(object: I): CreateTaskResponse {
    const message = createBaseCreateTaskResponse();
    message.task = (object.task !== undefined && object.task !== null) ? Task.fromPartial(object.task) : undefined;
    message.success = object.success ?? false;
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseRemoveTaskRequest(): RemoveTaskRequest {
  return { id: 0 };
}

export const RemoveTaskRequest: MessageFns<RemoveTaskRequest> = {
  encode(message: RemoveTaskRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RemoveTaskRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRemoveTaskRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RemoveTaskRequest {
    return { id: isSet(object.id) ? globalThis.Number(object.id) : 0 };
  },

  toJSON(message: RemoveTaskRequest): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RemoveTaskRequest>, I>>(base?: I): RemoveTaskRequest {
    return RemoveTaskRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RemoveTaskRequest>, I>>(object: I): RemoveTaskRequest {
    const message = createBaseRemoveTaskRequest();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseRemoveTaskResponse(): RemoveTaskResponse {
  return { success: false, message: "" };
}

export const RemoveTaskResponse: MessageFns<RemoveTaskResponse> = {
  encode(message: RemoveTaskResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RemoveTaskResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRemoveTaskResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RemoveTaskResponse {
    return {
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
    };
  },

  toJSON(message: RemoveTaskResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RemoveTaskResponse>, I>>(base?: I): RemoveTaskResponse {
    return RemoveTaskResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RemoveTaskResponse>, I>>(object: I): RemoveTaskResponse {
    const message = createBaseRemoveTaskResponse();
    message.success = object.success ?? false;
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseEditTaskRequest(): EditTaskRequest {
  return { id: 0, name: "", type: "", model: "" };
}

export const EditTaskRequest: MessageFns<EditTaskRequest> = {
  encode(message: EditTaskRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.type !== "") {
      writer.uint32(26).string(message.type);
    }
    if (message.model !== "") {
      writer.uint32(34).string(message.model);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EditTaskRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEditTaskRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.model = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EditTaskRequest {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      model: isSet(object.model) ? globalThis.String(object.model) : "",
    };
  },

  toJSON(message: EditTaskRequest): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.type !== "") {
      obj.type = message.type;
    }
    if (message.model !== "") {
      obj.model = message.model;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EditTaskRequest>, I>>(base?: I): EditTaskRequest {
    return EditTaskRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EditTaskRequest>, I>>(object: I): EditTaskRequest {
    const message = createBaseEditTaskRequest();
    message.id = object.id ?? 0;
    message.name = object.name ?? "";
    message.type = object.type ?? "";
    message.model = object.model ?? "";
    return message;
  },
};

function createBaseEditTaskResponse(): EditTaskResponse {
  return { task: undefined, success: false, message: "" };
}

export const EditTaskResponse: MessageFns<EditTaskResponse> = {
  encode(message: EditTaskResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.task !== undefined) {
      Task.encode(message.task, writer.uint32(10).fork()).join();
    }
    if (message.success !== false) {
      writer.uint32(16).bool(message.success);
    }
    if (message.message !== "") {
      writer.uint32(26).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EditTaskResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEditTaskResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.task = Task.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EditTaskResponse {
    return {
      task: isSet(object.task) ? Task.fromJSON(object.task) : undefined,
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
    };
  },

  toJSON(message: EditTaskResponse): unknown {
    const obj: any = {};
    if (message.task !== undefined) {
      obj.task = Task.toJSON(message.task);
    }
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EditTaskResponse>, I>>(base?: I): EditTaskResponse {
    return EditTaskResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EditTaskResponse>, I>>(object: I): EditTaskResponse {
    const message = createBaseEditTaskResponse();
    message.task = (object.task !== undefined && object.task !== null) ? Task.fromPartial(object.task) : undefined;
    message.success = object.success ?? false;
    message.message = object.message ?? "";
    return message;
  },
};

function createBasePauseTaskRequest(): PauseTaskRequest {
  return { id: 0 };
}

export const PauseTaskRequest: MessageFns<PauseTaskRequest> = {
  encode(message: PauseTaskRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PauseTaskRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePauseTaskRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PauseTaskRequest {
    return { id: isSet(object.id) ? globalThis.Number(object.id) : 0 };
  },

  toJSON(message: PauseTaskRequest): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PauseTaskRequest>, I>>(base?: I): PauseTaskRequest {
    return PauseTaskRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PauseTaskRequest>, I>>(object: I): PauseTaskRequest {
    const message = createBasePauseTaskRequest();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBasePauseTaskResponse(): PauseTaskResponse {
  return { task: undefined, success: false, message: "" };
}

export const PauseTaskResponse: MessageFns<PauseTaskResponse> = {
  encode(message: PauseTaskResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.task !== undefined) {
      Task.encode(message.task, writer.uint32(10).fork()).join();
    }
    if (message.success !== false) {
      writer.uint32(16).bool(message.success);
    }
    if (message.message !== "") {
      writer.uint32(26).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PauseTaskResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePauseTaskResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.task = Task.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PauseTaskResponse {
    return {
      task: isSet(object.task) ? Task.fromJSON(object.task) : undefined,
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
    };
  },

  toJSON(message: PauseTaskResponse): unknown {
    const obj: any = {};
    if (message.task !== undefined) {
      obj.task = Task.toJSON(message.task);
    }
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PauseTaskResponse>, I>>(base?: I): PauseTaskResponse {
    return PauseTaskResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PauseTaskResponse>, I>>(object: I): PauseTaskResponse {
    const message = createBasePauseTaskResponse();
    message.task = (object.task !== undefined && object.task !== null) ? Task.fromPartial(object.task) : undefined;
    message.success = object.success ?? false;
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseStopTaskRequest(): StopTaskRequest {
  return { id: 0 };
}

export const StopTaskRequest: MessageFns<StopTaskRequest> = {
  encode(message: StopTaskRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StopTaskRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStopTaskRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StopTaskRequest {
    return { id: isSet(object.id) ? globalThis.Number(object.id) : 0 };
  },

  toJSON(message: StopTaskRequest): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StopTaskRequest>, I>>(base?: I): StopTaskRequest {
    return StopTaskRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StopTaskRequest>, I>>(object: I): StopTaskRequest {
    const message = createBaseStopTaskRequest();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseStopTaskResponse(): StopTaskResponse {
  return { task: undefined, success: false, message: "" };
}

export const StopTaskResponse: MessageFns<StopTaskResponse> = {
  encode(message: StopTaskResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.task !== undefined) {
      Task.encode(message.task, writer.uint32(10).fork()).join();
    }
    if (message.success !== false) {
      writer.uint32(16).bool(message.success);
    }
    if (message.message !== "") {
      writer.uint32(26).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StopTaskResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStopTaskResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.task = Task.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StopTaskResponse {
    return {
      task: isSet(object.task) ? Task.fromJSON(object.task) : undefined,
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
    };
  },

  toJSON(message: StopTaskResponse): unknown {
    const obj: any = {};
    if (message.task !== undefined) {
      obj.task = Task.toJSON(message.task);
    }
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StopTaskResponse>, I>>(base?: I): StopTaskResponse {
    return StopTaskResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StopTaskResponse>, I>>(object: I): StopTaskResponse {
    const message = createBaseStopTaskResponse();
    message.task = (object.task !== undefined && object.task !== null) ? Task.fromPartial(object.task) : undefined;
    message.success = object.success ?? false;
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseInvoice(): Invoice {
  return { id: "", date: "", amount: 0, status: "" };
}

export const Invoice: MessageFns<Invoice> = {
  encode(message: Invoice, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.date !== "") {
      writer.uint32(18).string(message.date);
    }
    if (message.amount !== 0) {
      writer.uint32(25).double(message.amount);
    }
    if (message.status !== "") {
      writer.uint32(34).string(message.status);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Invoice {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseInvoice();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.date = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.amount = reader.double();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.status = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Invoice {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      date: isSet(object.date) ? globalThis.String(object.date) : "",
      amount: isSet(object.amount) ? globalThis.Number(object.amount) : 0,
      status: isSet(object.status) ? globalThis.String(object.status) : "",
    };
  },

  toJSON(message: Invoice): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.date !== "") {
      obj.date = message.date;
    }
    if (message.amount !== 0) {
      obj.amount = message.amount;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Invoice>, I>>(base?: I): Invoice {
    return Invoice.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Invoice>, I>>(object: I): Invoice {
    const message = createBaseInvoice();
    message.id = object.id ?? "";
    message.date = object.date ?? "";
    message.amount = object.amount ?? 0;
    message.status = object.status ?? "";
    return message;
  },
};

function createBaseGetBillingRequest(): GetBillingRequest {
  return {};
}

export const GetBillingRequest: MessageFns<GetBillingRequest> = {
  encode(_: GetBillingRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetBillingRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetBillingRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetBillingRequest {
    return {};
  },

  toJSON(_: GetBillingRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GetBillingRequest>, I>>(base?: I): GetBillingRequest {
    return GetBillingRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetBillingRequest>, I>>(_: I): GetBillingRequest {
    const message = createBaseGetBillingRequest();
    return message;
  },
};

function createBaseGetBillingResponse(): GetBillingResponse {
  return { invoices: [], currentMonthSpending: 0, hourlyRate: 0, dailySpending: [], resourceUsage: [] };
}

export const GetBillingResponse: MessageFns<GetBillingResponse> = {
  encode(message: GetBillingResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.invoices) {
      Invoice.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.currentMonthSpending !== 0) {
      writer.uint32(17).double(message.currentMonthSpending);
    }
    if (message.hourlyRate !== 0) {
      writer.uint32(25).double(message.hourlyRate);
    }
    writer.uint32(34).fork();
    for (const v of message.dailySpending) {
      writer.double(v);
    }
    writer.join();
    writer.uint32(42).fork();
    for (const v of message.resourceUsage) {
      writer.int32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetBillingResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetBillingResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.invoices.push(Invoice.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.currentMonthSpending = reader.double();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.hourlyRate = reader.double();
          continue;
        }
        case 4: {
          if (tag === 33) {
            message.dailySpending.push(reader.double());

            continue;
          }

          if (tag === 34) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.dailySpending.push(reader.double());
            }

            continue;
          }

          break;
        }
        case 5: {
          if (tag === 40) {
            message.resourceUsage.push(reader.int32());

            continue;
          }

          if (tag === 42) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.resourceUsage.push(reader.int32());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetBillingResponse {
    return {
      invoices: globalThis.Array.isArray(object?.invoices) ? object.invoices.map((e: any) => Invoice.fromJSON(e)) : [],
      currentMonthSpending: isSet(object.currentMonthSpending)
        ? globalThis.Number(object.currentMonthSpending)
        : isSet(object.current_month_spending)
        ? globalThis.Number(object.current_month_spending)
        : 0,
      hourlyRate: isSet(object.hourlyRate)
        ? globalThis.Number(object.hourlyRate)
        : isSet(object.hourly_rate)
        ? globalThis.Number(object.hourly_rate)
        : 0,
      dailySpending: globalThis.Array.isArray(object?.dailySpending)
        ? object.dailySpending.map((e: any) => globalThis.Number(e))
        : globalThis.Array.isArray(object?.daily_spending)
        ? object.daily_spending.map((e: any) => globalThis.Number(e))
        : [],
      resourceUsage: globalThis.Array.isArray(object?.resourceUsage)
        ? object.resourceUsage.map((e: any) => globalThis.Number(e))
        : globalThis.Array.isArray(object?.resource_usage)
        ? object.resource_usage.map((e: any) => globalThis.Number(e))
        : [],
    };
  },

  toJSON(message: GetBillingResponse): unknown {
    const obj: any = {};
    if (message.invoices?.length) {
      obj.invoices = message.invoices.map((e) => Invoice.toJSON(e));
    }
    if (message.currentMonthSpending !== 0) {
      obj.currentMonthSpending = message.currentMonthSpending;
    }
    if (message.hourlyRate !== 0) {
      obj.hourlyRate = message.hourlyRate;
    }
    if (message.dailySpending?.length) {
      obj.dailySpending = message.dailySpending;
    }
    if (message.resourceUsage?.length) {
      obj.resourceUsage = message.resourceUsage.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetBillingResponse>, I>>(base?: I): GetBillingResponse {
    return GetBillingResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetBillingResponse>, I>>(object: I): GetBillingResponse {
    const message = createBaseGetBillingResponse();
    message.invoices = object.invoices?.map((e) => Invoice.fromPartial(e)) || [];
    message.currentMonthSpending = object.currentMonthSpending ?? 0;
    message.hourlyRate = object.hourlyRate ?? 0;
    message.dailySpending = object.dailySpending?.map((e) => e) || [];
    message.resourceUsage = object.resourceUsage?.map((e) => e) || [];
    return message;
  },
};

export interface BillingService {
  GetBilling(request: GetBillingRequest): Promise<GetBillingResponse>;
}

export const BillingServiceServiceName = "sewers.BillingService";
export class BillingServiceClientImpl implements BillingService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || BillingServiceServiceName;
    this.rpc = rpc;
    this.GetBilling = this.GetBilling.bind(this);
  }
  GetBilling(request: GetBillingRequest): Promise<GetBillingResponse> {
    const data = GetBillingRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetBilling", data);
    return promise.then((data) => GetBillingResponse.decode(new BinaryReader(data)));
  }
}

export interface DashboardService {
  GetConfig(request: GetConfigRequest): Promise<ConfigResponse>;
  StreamMetrics(request: GetConfigRequest): Observable<Metrics>;
}

export const DashboardServiceServiceName = "sewers.DashboardService";
export class DashboardServiceClientImpl implements DashboardService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || DashboardServiceServiceName;
    this.rpc = rpc;
    this.GetConfig = this.GetConfig.bind(this);
    this.StreamMetrics = this.StreamMetrics.bind(this);
  }
  GetConfig(request: GetConfigRequest): Promise<ConfigResponse> {
    const data = GetConfigRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetConfig", data);
    return promise.then((data) => ConfigResponse.decode(new BinaryReader(data)));
  }

  StreamMetrics(request: GetConfigRequest): Observable<Metrics> {
    const data = GetConfigRequest.encode(request).finish();
    const result = this.rpc.serverStreamingRequest(this.service, "StreamMetrics", data);
    return result.pipe(map((data) => Metrics.decode(new BinaryReader(data))));
  }
}

export interface TaskService {
  GetTasks(request: GetTasksRequest): Promise<GetTasksResponse>;
  CreateTask(request: CreateTaskRequest): Promise<CreateTaskResponse>;
  StreamTaskProgress(request: GetTasksRequest): Observable<Task>;
  RemoveTask(request: RemoveTaskRequest): Promise<RemoveTaskResponse>;
  EditTask(request: EditTaskRequest): Promise<EditTaskResponse>;
  PauseTask(request: PauseTaskRequest): Promise<PauseTaskResponse>;
  StopTask(request: StopTaskRequest): Promise<StopTaskResponse>;
}

export const TaskServiceServiceName = "sewers.TaskService";
export class TaskServiceClientImpl implements TaskService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || TaskServiceServiceName;
    this.rpc = rpc;
    this.GetTasks = this.GetTasks.bind(this);
    this.CreateTask = this.CreateTask.bind(this);
    this.StreamTaskProgress = this.StreamTaskProgress.bind(this);
    this.RemoveTask = this.RemoveTask.bind(this);
    this.EditTask = this.EditTask.bind(this);
    this.PauseTask = this.PauseTask.bind(this);
    this.StopTask = this.StopTask.bind(this);
  }
  GetTasks(request: GetTasksRequest): Promise<GetTasksResponse> {
    const data = GetTasksRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetTasks", data);
    return promise.then((data) => GetTasksResponse.decode(new BinaryReader(data)));
  }

  CreateTask(request: CreateTaskRequest): Promise<CreateTaskResponse> {
    const data = CreateTaskRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "CreateTask", data);
    return promise.then((data) => CreateTaskResponse.decode(new BinaryReader(data)));
  }

  StreamTaskProgress(request: GetTasksRequest): Observable<Task> {
    const data = GetTasksRequest.encode(request).finish();
    const result = this.rpc.serverStreamingRequest(this.service, "StreamTaskProgress", data);
    return result.pipe(map((data) => Task.decode(new BinaryReader(data))));
  }

  RemoveTask(request: RemoveTaskRequest): Promise<RemoveTaskResponse> {
    const data = RemoveTaskRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "RemoveTask", data);
    return promise.then((data) => RemoveTaskResponse.decode(new BinaryReader(data)));
  }

  EditTask(request: EditTaskRequest): Promise<EditTaskResponse> {
    const data = EditTaskRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "EditTask", data);
    return promise.then((data) => EditTaskResponse.decode(new BinaryReader(data)));
  }

  PauseTask(request: PauseTaskRequest): Promise<PauseTaskResponse> {
    const data = PauseTaskRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "PauseTask", data);
    return promise.then((data) => PauseTaskResponse.decode(new BinaryReader(data)));
  }

  StopTask(request: StopTaskRequest): Promise<StopTaskResponse> {
    const data = StopTaskRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "StopTask", data);
    return promise.then((data) => StopTaskResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
  clientStreamingRequest(service: string, method: string, data: Observable<Uint8Array>): Promise<Uint8Array>;
  serverStreamingRequest(service: string, method: string, data: Uint8Array): Observable<Uint8Array>;
  bidirectionalStreamingRequest(service: string, method: string, data: Observable<Uint8Array>): Observable<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
